# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
 push:
  branches: [ main ]

env:
 AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}

jobs:
 build:
  runs-on: ubuntu-20.04

  steps:
   - name: Checkout
     uses: actions/checkout@v3

   - name: create secret files
     working-directory: ./src/main/resources
     run: |
      touch application.properties
      echo "${{ secrets.APPLICATION_PROPERTIES }}" >> application.properties

   - name: Set up JDK 11
     uses: actions/setup-java@v3
     with:
      java-version: '11'

   - name: Grant execute permission for gradlew
     run: chmod +x gradlew
     shell: bash

   - name: Build with Gradle
     run : ./gradlew clean build --exclude-task test
     shell: bash

   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY}}
      bucket: ${{ secrets.AWS_BUCKET_NAME}}
      region: ap-northeast-2
 
    - name: Make zip file
     run: zip -r ./code-deploy.zip .

   - name: Upload to S3
     run: aws s3 cp --region ap-northeast-2 ./code-deploy.zip s3://$AWS_S3_BUCKET_NAME/code-deploy.zip

   - name: Code Deploy
     run: aws deploy create-deployment
      --application-name shop
      --deployment-config-name CodeDeployDefault.OneAtATime
      --deployment-group-name main
      --s3-location bucket=${{ secrets.AWS_S3_BUCKET_NAME }},bundleType=zip,key=code-deploy.zip
